// <auto-generated />
namespace BusBookingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TripmoduleanditsrelationwithBusmodule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TripmoduleanditsrelationwithBusmodule));
        
        string IMigrationMetadata.Id
        {
            get { return "202006080740116_Trip module and its relation with Bus module"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
