// <auto-generated />
namespace BusBookingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RelationbetweenTripmoduleandBusmodulev2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationbetweenTripmoduleandBusmodulev2));
        
        string IMigrationMetadata.Id
        {
            get { return "202006090650308_Relation between Trip module and Bus module v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
