// <auto-generated />
namespace BusBookingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BusandTriprelationupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BusandTriprelationupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202006092115456_Bus and Trip relation update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
