// <auto-generated />
namespace BusBookingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addfeedback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfeedback));
        
        string IMigrationMetadata.Id
        {
            get { return "202005170308598_addfeedback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
